### ISSUE TITLE
What's the best development method for this package?

### ISSUE THREAD

**Issue by hengzhe-zhang** [cavalab/feat#279]
I love this package very much, and this might be considered as the SOTA method in SR domain. However, the problem is that unlike most GP work which uses DEAP or ECJ as their basic framework. This work seems hard to modify. As a result, my question is, are there any guidelines to develop and make some contributions to this package? Specifically, since C++ is a compilation language, how can I seamlessly integrate my Python-based experimental modules to collaborate with this package?

**Comment by lacava** [comment]
Hi @zhenlingcn, thanks for your interest. 

> However, the problem is that unlike most GP work which uses DEAP or ECJ as their basic framework. This work seems hard to modify. 

DEAP and ECJ are nice and probably easier to extend than FEAT, and slower. But I think you'll find that nearly all SR methods in recent research are roll-your-own GP systems (e.g., there are ~15 SR methods in [SRBench](https://github.com/EpistasisLab/srbench), and only a few of them share a code-base). I don't think this is a good thing, and I do wish there was a general purpose, modern C++ framework for GP that was easy to extend. I'm working on one, but AFAIK there isn't one right now. 

> are there any guidelines to develop and make some contributions to this package?

At the moment, there aren't contribution guidelines because I am the sole developer. But I would welcome contributions. If there is a specific feature you'd like to add we can chat about how to go about it. The [cpp api](https://lacava.github.io/feat/cpp_api/) would be useful for that. I like the idea of adding a contribution guide. 

> Specifically, since C++ is a compilation language, how can I seamlessly integrate my Python-based experimental modules to collaborate with this package?

What does your module do? Can it interface with FEAT through the [Python API](https://lacava.github.io/feat/py_api.html) ? 
Just note that, at its core, this is a C++ library with a Python wrapper. So, depending on what you want to do, it might be easier to do it in C++ than in Python. You might also be able to use [pybind11](https://github.com/pybind/pybind11) to interface with it.

**Comment by zhenlingcn** [comment]
Thanks for your answer. As a matter of fact, I have no idea what I should do to improve the performance of this package. In my previous work, I used DEAP as the basic framework, and developed some new methods based on that. Although it is well-designed and handy, I feel the performance of that package is not satisfactory, which motivated me to find a new package. Therefore, I'm looking for a high-performance GP package for future research.
